# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

# To install the git pre-commit hooks run:
#   pre-commit install --install-hooks
# To update the versions:
#   pre-commit autoupdate
default_stages:
  - commit
repos:
- hooks:
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-case-conflict
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.10.0
- hooks:
  - id: ansible-lint
  repo: https://github.com/ansible-community/ansible-lint
  rev: v25.12.1
-   repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
    -   id: reuse
